# See LICENSE file for copyright and license details
version = "2"

[linters]
default = "none"
enable = [
	"govet",
	"staticcheck",
	"misspell",
	"unparam",
]

[linters.settings.misspell]
locale = "US"

[linters.settings.staticcheck]
checks = [
	"all",
	"-SA1029",
	"-SA9003",
	"-ST1000",
	"-ST1003",
	"-ST1016",
	"-ST1020",
	"-ST1021",
	"-ST1022",
	"-ST1023",
]

[formatters]
enable = ["goimports"]
