# See LICENSE file for copyright and license details
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
-   repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
    -   id: golangci-lint-config-verify
    -   id: golangci-lint-fmt
    -   id: golangci-lint
-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
    -   id: markdownlint
