# See LICENSE file for copyright and license details
version: "3"

vars:
  GO: go

tasks:
  default:
    cmds:
      - task: fast

  fast:
    desc: run a fast lint/test suite (default)
    cmds:
      - task: golangci-lint
      - task: gotest

  ci:
    desc: run a full lint/test suite
    cmds:
      - task: default
      - task: govulncheck

  gotest:
    desc: (lint, fast) run go test
    requires:
      vars: [GO]
    cmds:
      - "{{.GO}} test ./..."

  golangci-lint:
    desc: (lint, fast) run golangci-lint
    preconditions:
      - sh: command -v golangci-lint
        msg: install golangci-lint and try again
    cmds:
      - golangci-lint run

  govulncheck:
    desc: (lint) run govulncheck
    preconditions:
      - sh: command -v govulncheck
        msg: run '{{.GO}} install golang.org/x/vuln/cmd/govulncheck@latest' and try again
    cmds:
      - govulncheck ./...
