version: "3"

vars:
  GO: go
  MISSPELL_FLAGS: -error -locale US
  STATICCHECK_FLAGS: -checks all,-SA1029,-SA9003,-ST1000,-ST1003,-ST1016,-ST1020,-ST1021,-ST1022,-ST1023

tasks:
  default:
    desc: run a fast lint/test suite
    deps: [staticcheck, misspell, unparam]
    requires:
      vars: [GO]
    cmds:
      - "{{.GO}} vet ./..."
      - "{{.GO}} test ./..."

  full:
    desc: run a full lint/test suite
    deps: [default, govulncheck]

  staticcheck:
    desc: (lint, fast) run staticcheck
    preconditions:
      - sh: command -v staticcheck
        msg: run '{{.GO}} install honnef.co/go/tools/cmd/staticcheck@latest' and try again
    cmds:
      - "staticcheck {{.STATICCHECK_FLAGS}} ./..."

  misspell:
    desc: (lint, fast) run misspell
    preconditions:
      - sh: command -v misspell
        msg: run '{{.GO}} install github.com/client9/misspell/cmd/misspell@latest' and try again
    shopt: [globstar]
    cmds:
      - misspell {{.MISSPELL_FLAGS}} -source go **/*.go
      - misspell {{.MISSPELL_FLAGS}} CHANGELOG CONTRIBUTING LICENSE README

  unparam:
    desc: (lint, fast) run unparam
    preconditions:
      - sh: command -v unparam
        msg: run '{{.GO}} install mvdan.cc/unparam@latest' and try again
    cmds:
      - unparam ./...

  govulncheck:
    desc: (lint) run govulncheck
    preconditions:
      - sh: command -v govulncheck
        msg: run '{{.GO}} install golang.org/x/vuln/cmd/govulncheck@latest' and try again
    cmds:
      - govulncheck ./...
