# See LICENSE file for copyright and license information
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'

    - name: Setup go-task
      uses: lukeshay/setup-task@v1    

    - name: Test
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install github.com/client9/misspell/cmd/misspell@latest
        go install mvdan.cc/unparam@latest
        go install golang.org/x/vuln/cmd/govulncheck@latest
        task ci
